version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - pixi_cache:/home/vscode/.pixi/envs
    ports:
      - "8501:8501"

    # Убедитесь, что у вас установлен NVIDIA Container Toolkit на хосте
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    stdin_open: true
    tty: true

  volumes:
    pixi_cache: